CREATE TABLE games (
  ID int NOT NULL AUTO_INCREMENT,
  season_id int NOT NULL,
  date_of_game date NOT NULL,
  away_name VARCHAR(256) NOT NULL,
  away_hits int DEFAULT 0,
  away_errors int DEFAULT 0,
  home_name VARCHAR(256) NOT NULL,
  home_hits int DEFAULT 0,
  home_errors int DEFAULT 0,
  win int DEFAULT 0,
  loss int DEFAULT 0,
  tie int DEFAULT 0,
  winning_pitcher int,
  losing_pitcher int,
  saving_pitcher int,
  top_first int DEFAULT 0,
  bottom_first int DEFAULT 0,
  top_second int DEFAULT 0,
  bottom_second int DEFAULT 0,
  top_third int DEFAULT 0,
  bottom_third int DEFAULT 0,
  top_fourth int DEFAULT 0,
  bottom_fourth int DEFAULT 0,
  top_fifth int DEFAULT 0,
  bottom_fifth int DEFAULT 0,
  top_sixth int DEFAULT 0,
  bottom_sixth int DEFAULT 0,
  top_seventh int DEFAULT 0,
  bottom_seventh int DEFAULT 0,
  top_eighth int DEFAULT 0,
  bottom_eighth int DEFAULT 0,
  top_ninth int DEFAULT 0,
  bottom_ninth int DEFAULT 0,
  top_tenth int DEFAULT 0,
  bottom_tenth int DEFAULT 0,
  away_runs int as (top_first + top_second + top_third + top_fourth + top_fifth + top_sixth + top_seventh + top_eighth + top_ninth + top_tenth),
  home_runs int as (bottom_first + bottom_second + bottom_third + bottom_fourth + bottom_fifth + bottom_sixth + bottom_seventh + bottom_eighth + bottom_ninth + bottom_tenth),
  PRIMARY KEY (ID) 
);
