# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d14b1c5826e87a3fca93968765d46a4c8813c25f718f0fd1d24f44cdec1196f46b025b045f5c6412061da0f7011bb5fe3d2b7db5dc1650a122d2ec96b8674383
  db_user: dtokita 
  db_password: password

test:
  secret_key_base: 4c68ed2faa71dac6bce5380e31e5d02473b0ad6fcabaafabc9e8e606697b57d5d7de7ff17019eb63fbf87664e26b2c934c44fdff7618adb63a3b04e14df47475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
