CREATE TABLE offstats (
  ID int NOT NULL AUTO_INCREMENT,
  player_id int NOT NULL,
  game_id int NOT NULL,
  season_id int NOT NULL,
  plate_appearances double DEFAULT 0.0,
  at_bats double DEFAULT 0.0,
  runs double DEFAULT 0.0,
  hits double DEFAULT 0.0,
  singles double DEFAULT 0.0,
  doubles double DEFAULT 0.0,
  triples double DEFAULT 0.0,
  homeruns double DEFAULT 0.0,
  rbis double DEFAULT 0.0,
  walks double DEFAULT 0.0,
  hit_by_pitches double DEFAULT 0.0,
  strikeouts double DEFAULT 0.0,
  stolen_bases double DEFAULT 0.0,
  caught_stealings double DEFAULT 0.0,
  batting_average double AS (hits / at_bats),
  on_base_percentage double AS ((hits + walks) / plate_appearances),
  slugging_percentage double AS ((singles + 2 * doubles + 3 * triples + 4 * homeruns) / at_bats),
  PRIMARY KEY (ID)
);
